/**
 * Enemy Configuration
 * 
 * Contains all enemy type definitions including base stats,
 * visual properties, and behavior configurations.
 */

export const enemiesConfig = [
    {
        key: 'enemy_favela_basico',
        enemy_body_image: 'src/assets/images/enemy_favela_basico.png',
        enemy_legs_image: 'src/assets/images/enemy_favela_basico_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 100,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.8,
        legsScale: 0.5,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'zigzag',
            behaviorParams: {
                baseSpeed: 1.0,             // Normal forward speed
                amplitude: 50,              // 50px lateral movement
                frequency: 3.0              // Oscillates 3 times per second
            }
        },
        scalingProfile: 'swarm'
    },
    {
        key: 'enemy_bandido',
        enemy_body_image: 'src/assets/images/enemy_bandido.png',
        enemy_legs_image: 'src/assets/images/enemy_bandido_legs.png',
        speed: 200,
        size: 32,
        damage: 10,
        health: 80,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.7,
        legsScale: 0.4,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: -10, y: 30 },
        hitSoundKey: 'hit',
        dropChance: 0.08,
        lootTable: 'common',
        ai: {
            behaviorKey: 'burst_pursuit',
            behaviorParams: {
                pursuitSpeed: 1.5,          // 1.5x speed during pursuit
                pursuitDuration: 1000,      // Pursue for 1.5s
                pauseDuration: 800,         // Pause for 0.8s
                pauseSpeed: 0               // Completely stop during pause
            }
        },
        scalingProfile: 'aggressive'
    },
    {
        key: 'enemy_bandido2',
        enemy_body_image: 'src/assets/images/enemy_bandido2.png',
        enemy_legs_image: 'src/assets/images/enemy_bandido2_legs.png',
        speed: 200,
        size: 32,
        damage: 15,
        health: 150,
        spawnDistance: 700,
        maxOnScreen: 40,
        xpDropChance: 0.9,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 0.8,
        legsScale: 0.5,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common',
        ai: {
            behaviorKey: 'charge',
            behaviorParams: {
                chargeUpTime: 800,          // 0.8s wind-up
                chargeSpeed: 3.0,           // 3x normal speed during charge
                chargeDuration: 500,        // Charge lasts 0.5s
                cooldownTime: 1500,         // 1.5s before next charge
                idleSpeed: 0.3,             // Slow approach between charges
                lockDirection: true         // Direction locked at charge start
            }
        },
        scalingProfile: 'aggressive'
    },
    {
        key: 'enemy_bolsonarista',
        enemy_body_image: 'src/assets/images/enemy_bolsonarista.png',
        enemy_legs_image: 'src/assets/images/enemy_bolsonarista_legs.png',
        speed: 250,
        size: 32,
        damage: 20,
        health: 40,
        spawnDistance: 700,
        maxOnScreen: 30,
        xpDropChance: 0.85,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 3,
        bodyScale: 1,
        legsScale: 1,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 5, y: 45 },
        hitSoundKey: 'hit',
        dropChance: 0.15,
        lootTable: 'ucommon',
        ai: {
            behaviorKey: 'orbit',
            behaviorParams: {
                preferredDistance: 200,     // Stay 200px from player
                orbitSpeed: 0.8,            // Orbit at 80% speed
                approachSpeed: 1.0,         // Full speed when approaching
                orbitDirection: 1,          // Clockwise
                distanceTolerance: 30       // 30px tolerance before adjusting
            }
        },
        scalingProfile: 'ranged'
    },
    {
        key: 'enemy_bolsonarista2',
        enemy_body_image: 'src/assets/images/enemy_bolsonarista2.png',
        enemy_legs_image: 'src/assets/images/enemy_bolsonarista2_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.45,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: -10, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common',
        ai: {
            behaviorKey: 'chase',
            behaviorParams: {
                speed: 1.0,                 // Normal speed
                trackingSpeed: 1.0,         // Instant direction updates
                minDistance: 0              // Chase all the way to player
            }
        }
    },
    {
        key: 'enemy_centrao',
        enemy_body_image: 'src/assets/images/enemy_centrao.png',
        enemy_legs_image: 'src/assets/images/enemy_centrao_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.7,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_comunista',
        enemy_body_image: 'src/assets/images/enemy_comunista.png',
        enemy_legs_image: 'src/assets/images/enemy_comunista_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 0.9,
        legsScale: 0.6,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_favela',
        enemy_body_image: 'src/assets/images/enemy_favela.png',
        enemy_legs_image: 'src/assets/images/enemy_favela_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.4,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_feminista',
        enemy_body_image: 'src/assets/images/enemy_feminista.png',
        enemy_legs_image: 'src/assets/images/enemy_feminista_doida_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.45,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_feminista_doida',
        enemy_body_image: 'src/assets/images/enemy_feminista_doida.png',
        enemy_legs_image: 'src/assets/images/enemy_feminista_doida_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.45,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_history_teacher',
        enemy_body_image: 'src/assets/images/enemy_history_teacher.png',
        enemy_legs_image: 'src/assets/images/enemy_history_teacher_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.3,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_history_teacher2',
        enemy_body_image: 'src/assets/images/enemy_history_teacher2.png',
        enemy_legs_image: 'src/assets/images/enemy_history_teacher2_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.3,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_mendigo',
        enemy_body_image: 'src/assets/images/enemy_mendigo.png',
        enemy_legs_image: 'src/assets/images/enemy_mendigo_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.7,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_partido_amarelo',
        enemy_body_image: 'src/assets/images/enemy_partido_amarelo.png',
        enemy_legs_image: 'src/assets/images/enemy_petista_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 0.9,
        legsScale: 0.4,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_partido_amarelo2',
        enemy_body_image: 'src/assets/images/enemy_partido_amarelo2.png',
        enemy_legs_image: 'src/assets/images/enemy_petista_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 0.9,
        legsScale: 0.4,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_petista',
        enemy_body_image: 'src/assets/images/enemy_petista.png',
        enemy_legs_image: 'src/assets/images/enemy_petista_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 0.9,
        legsScale: 0.4,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_politico',
        enemy_body_image: 'src/assets/images/enemy_politico.png',
        enemy_legs_image: 'src/assets/images/enemy_politico_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.25,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_elite_bandido',
        enemy_body_image: 'src/assets/images/enemy_elite_bandido.png',
        enemy_legs_image: 'src/assets/images/enemy_elite_bandido_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 0.7,
        legsScale: 0.7,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        isElite: true,
        lootTable: 'common'
    },
    {
        key: 'enemy_tia_zap',
        enemy_body_image: 'src/assets/images/boss_tia_zap.png',
        enemy_legs_image: 'src/assets/images/enemy_tia_zap_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 0.9,
        legsScale: 0.6,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 20 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_karl_marx',
        enemy_body_image: 'src/assets/images/boss_karl_marx.png',
        enemy_legs_image: 'src/assets/images/enemy_politico_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 0.7,
        legsScale: 0.2,
        bodyWidth: 60,
        bodyHeight: 100,
        bossScale: 0.6,
        legOffset: { x: 0, y: 0 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_bandido_moto',
        enemy_body_image: 'src/assets/images/boss_bandido_moto.png',
        enemy_legs_image: 'src/assets/images/enemy_politico_legs.png',
        speed: 240,
        size: 32,
        damage: 8,
        health: 100,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 0.8,
        legsScale: 0.1,
        bodyWidth: 60,
        bodyHeight: 100,
        bossScale: 0.6,
        legOffset: { x: 0, y: 0 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_tia_do_zap',
        enemy_body_image: 'src/assets/images/enemy_tia_do_zap.png',
        enemy_legs_image: 'src/assets/images/enemy_tia_zap_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 0.9,
        legsScale: 0.6,
        bodyWidth: 60,
        bodyHeight: 100,
        bossScale: 0.6,
        legOffset: { x: 5, y: 0 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    }
];

/**
 * Boss Configuration
 */
export const bossesConfig = [
    {
        key: 'boss_tia_zap',
        name: 'Tia do Zap',
        baseEnemy: 'enemy_tia_zap',
        healthMultiplier: 2,
        damageMultiplier: 2,
        speedMultiplier: 0.7,
        sizeMultiplier: 1.2,
        xpDropChance: 1.0,
        xpValue: 2,
        tint: 0xFFFFFF,
        enrageTint: 0xFF0000,
        enrageHealthThreshold: 0.5,
        enrageSpeedBonus: 0.2,
        stompInterval: 2000,
        gameplayRhythm: 0.5,
        dropChance: 1.0,
        lootTable: 'boss'
    },
    {
        key: 'boss_karl_marx',
        name: 'Karl Marx',
        baseEnemy: 'enemy_karl_marx',
        healthMultiplier: 2,
        damageMultiplier: 2,
        speedMultiplier: 0.7,
        sizeMultiplier: 1.2,
        xpDropChance: 1.0,
        xpValue: 2,
        tint: 0xFFFFFF,
        enrageTint: 0xFF0000,
        enrageHealthThreshold: 0.5,
        enrageSpeedBonus: 0.2,
        stompInterval: 2000,
        gameplayRhythm: 0.5,
        dropChance: 1.0,
        lootTable: 'boss'
    },
    {
        key: 'boss_bandido_moto',
        name: 'Dois homens numa moto',
        baseEnemy: 'enemy_bandido_moto',
        healthMultiplier: 2,
        damageMultiplier: 2,
        speedMultiplier: 0.7,
        sizeMultiplier: 1.6,
        xpDropChance: 1.0,
        xpValue: 2,
        tint: 0xFFFFFF,
        enrageTint: 0xFF0000,
        enrageHealthThreshold: 0.5,
        enrageSpeedBonus: 0.2,
        stompInterval: 2000,
        gameplayRhythm: 0.5,
        dropChance: 1.0,
        lootTable: 'boss'
    },
    {
        key: 'boss_tia_do_zap',
        name: 'Tia do Zap',
        baseEnemy: 'enemy_tia_do_zap',
        healthMultiplier: 2,
        damageMultiplier: 2,
        speedMultiplier: 0.7,
        sizeMultiplier: 1.5,
        xpDropChance: 1.0,
        xpValue: 2,
        tint: 0xFFFFFF,
        enrageTint: 0xFF0000,
        enrageHealthThreshold: 0.5,
        enrageSpeedBonus: 0.2,
        stompInterval: 2000,
        gameplayRhythm: 0.5,
        dropChance: 1.0,
        lootTable: 'boss'
    }
];
