/**
 * Enemy Configuration
 * 
 * Contains all enemy type definitions including base stats,
 * visual properties, and behavior configurations.
 */

export const enemiesConfig = [
    /* ------------ Enemies Favela ------------ */
    {
        key: 'enemy_favela_basico',
        enemy_body_image: 'src/assets/images/enemy_favela_basico.png',
        enemy_legs_image: 'src/assets/images/enemy_favela_basico_legs.png',
        speed: 100,
        size: 32,
        damage: 5,
        health: 100,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.6,
        legsScale: 0.3,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 30 },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'zigzag',
            behaviorParams: {
                baseSpeed: 0.5,
                amplitude: 500,
                frequency: 3.0
            }
        },
        scalingProfile: 'swarm'
    },
    {
        key: 'enemy_favela',
        enemy_body_image: 'src/assets/images/enemy_favela.png',
        enemy_legs_image: 'src/assets/images/enemy_favela_legs.png',
        speed: 100,
        size: 32,
        damage: 5,
        health: 50,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.85,
        legsScale: 0.3,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 5, y: 40 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common',
        ai: {
            behaviorKey: 'chase',
            behaviorParams: {
                speed: 0.6,
                trackingSpeed: 0.8
            }
        }
    },
    {
        key: 'enemy_mendigo',
        enemy_body_image: 'src/assets/images/enemy_mendigo.png',
        enemy_legs_image: 'src/assets/images/enemy_mendigo_legs.png',
        speed: 80,
        size: 32,
        damage: 8,
        health: 40,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.85,
        legsScale: 0.55,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common',
        ai: {
            behaviorKey: 'zigzag',
            behaviorParams: {
                baseSpeed: 0.8,
                amplitude: 100,
                frequency: 1.5
            }
        }
    },
    {
        key: 'enemy_mandraka',
        enemy_body_image: 'src/assets/images/enemy_mandraka.png',
        enemy_legs_image: 'src/assets/images/enemy_mandraka_legs.png',
        speed: 70,
        size: 32,
        damage: 5,
        health: 150,
        spawnDistance: 700,
        maxOnScreen: 40,
        xpDropChance: 0.9,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.8,
        legsScale: 0.5,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common',
        ai: {
            behaviorKey: 'chase',
            behaviorParams: {
                speed: 0.8,
                trackingSpeed: 0.4
            }
        },
        scalingProfile: 'aggressive'
    },
    {
        key: 'enemy_bolsa_familia',
        enemy_body_image: 'src/assets/images/enemy_bolsa_familia.png',
        enemy_legs_image: 'src/assets/images/enemy_bolsa_familia_legs.png',
        speed: 100,
        size: 32,
        damage: 5,
        health: 100,
        spawnDistance: 700,
        maxOnScreen: 40,
        xpDropChance: 0.9,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.8,
        legsScale: 0.5,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common',
        ai: {
            behaviorKey: 'chase',
            behaviorParams: {
                speed: 0.8,
                trackingSpeed: 0.4
            }
        },
        scalingProfile: 'aggressive'
    },
    {
        key: 'enemy_elite_bandido',
        enemy_body_image: 'src/assets/images/enemy_elite_bandido.png',
        enemy_legs_image: 'src/assets/images/enemy_elite_bandido_legs.png',
        speed: 140,
        size: 32,
        damage: 15,
        health: 200,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.7,
        legsScale: 0.7,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0xFF5500,
        projectileScale: 1.2,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        isElite: true,
        lootTable: 'common',
        ai: {
            behaviorKey: 'charge',
            behaviorParams: {
                chargeUpTime: 2000,
                chargeSpeed: 3.0,
                chargeDuration: 500,
                cooldownTime: 1500,
                idleSpeed: 0.3,
                lockDirection: true
            }
        },
        scalingProfile: 'ranged'
    },
    {
        key: 'enemy_bandido_moto',
        enemy_body_image: 'src/assets/images/enemy_bandido_moto.png',
        enemy_legs_image: 'src/assets/images/enemy_bandido_legs.png',
        speed: 300,
        size: 35,
        damage: 25,
        health: 500,
        spawnDistance: 700,
        maxOnScreen: 5,
        xpDropChance: 1.0,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 20,
        bodyScale: 0.8,
        legsScale: 0,
        bodyWidth: 70,
        bodyHeight: 110,
        hitbox: { width: 150, height: 190 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0xFFFFFF,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.2,
        isElite: true,
        lootTable: 'rare',
        ai: {
            behaviorKey: 'charge',
            behaviorParams: {
                chargeUpTime: 800,
                chargeSpeed: 3.0,
                chargeDuration: 500,
                cooldownTime: 1500,
                idleSpeed: 0.3,
                lockDirection: true
            }
        },
        scalingProfile: 'aggressive'
    },
    {
        key: 'enemy_milicia',
        enemy_body_image: 'src/assets/images/enemy_milicia.png',
        enemy_legs_image: 'src/assets/images/enemy_milicia_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 100,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.8,
        legsScale: 0.5,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'chase',
            behaviorParams: {
                speed: 1.0,
                trackingSpeed: 0.4
            }
        },
        canShoot: true,
        projectileSpeed: 350,
        shootInterval: 2500,
        shootRange: 400,
        projectileDamage: 10
    },
    {
        key: 'enemy_milicia2',
        enemy_body_image: 'src/assets/images/enemy_milicia2.png',
        enemy_legs_image: 'src/assets/images/enemy_milicia_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 120,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.8,
        legsScale: 0.5,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0x00FF00,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'orbit',
            behaviorParams: {
                preferredDistance: 300,
                orbitSpeed: 0.7,
                approachSpeed: 1.0,
                orbitDirection: -1
            }
        }
    },
    {
        key: 'enemy_milicia3',
        enemy_body_image: 'src/assets/images/enemy_milicia3.png',
        enemy_legs_image: 'src/assets/images/enemy_milicia_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 120,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.8,
        legsScale: 0.5,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0x0000FF,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'zigzag',
            behaviorParams: {
                baseSpeed: 1.1,
                amplitude: 60,
                frequency: 2.5
            }
        }
    },
    {
        key: 'enemy_funkeiro',
        enemy_body_image: 'src/assets/images/enemy_funkeiro.png',
        enemy_legs_image: 'src/assets/images/enemy_funkeiro_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 100,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.8,
        legsScale: 0.5,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'charge',
            behaviorParams: {
                chargeUpTime: 1000,
                chargeSpeed: 2.5,
                chargeDuration: 600,
                cooldownTime: 2000,
                idleSpeed: 0.4
            }
        }
    },
    {
        key: 'enemy_funkeiro2',
        enemy_body_image: 'src/assets/images/enemy_funkeiro2.png',
        enemy_legs_image: 'src/assets/images/enemy_petista_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 100,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.8,
        legsScale: 0.4,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'burst_pursuit',
            behaviorParams: {
                pursuitSpeed: 1.6,
                pursuitDuration: 1000,
                pauseDuration: 500,
                pauseSpeed: 0.1
            }
        }
    },
    {
        key: 'enemy_funkeiro3',
        enemy_body_image: 'src/assets/images/enemy_funkeiro3.png',
        enemy_legs_image: 'src/assets/images/enemy_bandido_legs.png',
        speed: 180,
        size: 32,
        damage: 5,
        health: 60,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.7,
        legsScale: 0.4,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: -10, y: 30 },
        hitSoundKey: 'hit',
        dropChance: 0.08,
        lootTable: 'common',
        ai: {
            behaviorKey: 'burst_pursuit',
            behaviorParams: {
                pursuitSpeed: 1.5,
                pursuitDuration: 1000,
                pauseDuration: 800,
                pauseSpeed: 0
            }
        },
        scalingProfile: 'swarm'
    },
    {
        key: 'enemy_cria',
        enemy_body_image: 'src/assets/images/enemy_cria.png',
        enemy_legs_image: 'src/assets/images/enemy_cria_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 100,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.8,
        legsScale: 0.5,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'zigzag',
            behaviorParams: {
                baseSpeed: 0.8,
                amplitude: 10,
                frequency: 8.0
            }
        }
    },
    {
        key: 'enemy_cria2',
        enemy_body_image: 'src/assets/images/enemy_cria2.png',
        enemy_legs_image: 'src/assets/images/enemy_cria2_legs.png',
        speed: 100,
        size: 32,
        damage: 5,
        health: 100,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.8,
        legsScale: 0.5,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'zigzag',
            behaviorParams: {
                baseSpeed: 0.6,
                amplitude: 80,
                frequency: 4.0
            }
        }
    },
    {
        key: 'enemy_influencer',
        enemy_body_image: 'src/assets/images/enemy_influencer.png',
        enemy_legs_image: 'src/assets/images/enemy_influencer2_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 100,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.9,
        legsScale: 0.8,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 30 },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'orbit',
            behaviorParams: {
                preferredDistance: 400,
                orbitSpeed: 0.6,
                approachSpeed: 0.8,
                orbitDirection: 1
            }
        },
        canShoot: true,
        projectileSpeed: 250,
        shootInterval: 4000,
        shootRange: 500,
        projectileDamage: 15
    },
    {
        key: 'enemy_influencer2',
        enemy_body_image: 'src/assets/images/enemy_influencer2.png',
        enemy_legs_image: 'src/assets/images/enemy_influencer2_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 100,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: true,
        projectileSpeed: 300,
        shootInterval: 3000,
        shootRange: 400,
        projectileDamage: 12,
        xpValue: 1,
        bodyScale: 0.9,
        legsScale: 0.8,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0xFFFF00,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'orbit',
            behaviorParams: {
                preferredDistance: 350,
                orbitSpeed: 0.8,
                approachSpeed: 1.0,
                orbitDirection: -1
            }
        }
    },
    {
        key: 'enemy_crime',
        enemy_body_image: 'src/assets/images/enemy_crime.png',
        enemy_legs_image: 'src/assets/images/enemy_crime_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 100,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: true,
        projectileSpeed: 200,
        shootInterval: 1000,
        shootRange: 350,
        projectileDamage: 12,
        xpValue: 1,
        bodyScale: 0.9,
        legsScale: 0.6,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: -10, y: 40 },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'orbit',
            behaviorParams: {
                preferredDistance: 300,
                orbitSpeed: 0.7,
                approachSpeed: 1.0,
                orbitDirection: -1
            }
        }
    },
    {
        key: 'enemy_crime2',
        enemy_body_image: 'src/assets/images/enemy_crime2.png',
        enemy_legs_image: 'src/assets/images/enemy_crime4_legs.png',
        speed: 130,
        size: 32,
        damage: 10,
        health: 120,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: true,
        projectileSpeed: 200,
        shootInterval: 1000,
        shootRange: 350,
        projectileDamage: 12,
        xpValue: 1,
        bodyScale: 0.8,
        legsScale: 0.6,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: -5, y: 30 },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'orbit',
            behaviorParams: {
                preferredDistance: 250,
                orbitSpeed: 1.7,
                approachSpeed: 1.0,
                orbitDirection: -1
            }
        }
    },
    {
        key: 'enemy_crime3',
        enemy_body_image: 'src/assets/images/enemy_crime3.png',
        enemy_legs_image: 'src/assets/images/enemy_crime3_legs.png',
        speed: 100,
        size: 32,
        damage: 12,
        health: 150,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: true,
        projectileSpeed: 200,
        shootInterval: 1000,
        shootRange: 350,
        projectileDamage: 12,
        xpValue: 1,
        bodyScale: 0.9,
        legsScale: 0.6,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'charge',
            behaviorParams: {
                chargeUpTime: 100,
                chargeSpeed: 5.5,
                chargeDuration: 200,
                cooldownTime: 400,
                idleSpeed: 0
            }
        }
    },
    {
        key: 'enemy_crime4',
        enemy_body_image: 'src/assets/images/enemy_crime4.png',
        enemy_legs_image: 'src/assets/images/enemy_crime4_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 130,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.9,
        legsScale: 0.7,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 42 },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'burst_pursuit',
            behaviorParams: {
                pursuitSpeed: 1.8,
                pursuitDuration: 500,
                pauseDuration: 500,
                pauseSpeed: 0
            }
        }
    },
    {
        key: 'enemy_crime5',
        enemy_body_image: 'src/assets/images/enemy_crime5.png',
        enemy_legs_image: 'src/assets/images/enemy_crime_legs.png',
        speed: 200,
        size: 32,
        damage: 15,
        health: 150,
        spawnDistance: 700,
        maxOnScreen: 40,
        xpDropChance: 0.9,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 0.9,
        legsScale: 0.6,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 45 },
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common',
        ai: {
            behaviorKey: 'charge',
            behaviorParams: {
                chargeUpTime: 800,
                chargeSpeed: 3.0,
                chargeDuration: 500,
                cooldownTime: 1500,
                idleSpeed: 0.3,
                lockDirection: true
            }
        },
        scalingProfile: 'aggressive'
    },
    {
        key: 'enemy_boss_bandido',
        enemy_body_image: 'src/assets/images/boss_bandido.png',
        enemy_legs_image: 'src/assets/images/enemy_favela_legs.png',
        speed: 50,
        size: 64,
        damage: 20,
        health: 1000,
        canShoot: true,
        projectileSpeed: 400,
        shootInterval: 100,
        shootRange: 600,
        projectileDamage: 15,
        xpValue: 100,
        bodyScale: 0.8,
        legsScale: 0.1,
        hitbox: { width: 150, height: 190 },
        ai: {
            behaviorKey: 'stationary_burst',
            behaviorParams: {
                pauseDuration: 2500,
                shotsPerBurst: 15,
                fireRate: 80,
                idleSpeed: 0.1,
                telegraphDuration: 1200
            }
        }
    },
    {
        key: 'enemy_boss_milicia',
        enemy_body_image: 'src/assets/images/boss_milicia.png',
        enemy_legs_image: 'src/assets/images/enemy_milicia_legs.png',
        speed: 120,
        size: 64,
        damage: 25,
        health: 1000,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 120,
        bodyScale: 0.7,
        legsScale: 1.4,
        legOffset: { x: -10, y: 80 },
        hitbox: { width: 150, height: 190 },
        ai: {
            behaviorKey: 'tactical_chase',
            behaviorParams: {
                chaseDuration: 4000,
                repositionDuration: 3000,
                preferredDistance: 350,
                approachSpeed: 1.3,
                retreatSpeed: 0.9
            }
        }
    },
    {
        key: 'enemy_boss_funkeiro',
        enemy_body_image: 'src/assets/images/boss_funkeiro.png',
        enemy_legs_image: 'src/assets/images/enemy_funkeiro_legs.png',
        speed: 150,
        size: 64,
        damage: 20,
        health: 1000,
        canShoot: false,
        xpValue: 150,
        bodyScale: 0.7,
        legsScale: 1.4,
        legOffset: { x: 0, y: 90 },
        hitbox: { width: 150, height: 190 },
        ai: {
            behaviorKey: 'rhythmic_area',
            behaviorParams: {
                pulseInterval: 2800,
                orbitDuration: 2500,
                dashDuration: 400,
                dashSpeed: 4.0,
                orbitSpeed: 1.2,
                orbitDirection: 1
            }
        }
    },
    /* -----------------------------*/
    {
        key: 'enemy_bolsonarista',
        enemy_body_image: 'src/assets/images/enemy_bolsonarista.png',
        enemy_legs_image: 'src/assets/images/enemy_bolsonarista_legs.png',
        speed: 250,
        size: 32,
        damage: 20,
        health: 40,
        spawnDistance: 700,
        maxOnScreen: 30,
        xpDropChance: 0.85,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 3,
        bodyScale: 1,
        legsScale: 1,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 5, y: 45 },
        hitSoundKey: 'hit',
        dropChance: 0.15,
        lootTable: 'common',
        ai: {
            behaviorKey: 'orbit',
            behaviorParams: {
                preferredDistance: 200,
                orbitSpeed: 0.8,
                approachSpeed: 1.0,
                orbitDirection: 1,
                distanceTolerance: 30
            }
        },
        scalingProfile: 'ranged'
    },
    {
        key: 'enemy_bolsonarista2',
        enemy_body_image: 'src/assets/images/enemy_bolsonarista2.png',
        enemy_legs_image: 'src/assets/images/enemy_bolsonarista2_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.45,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: -10, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common',
        ai: {
            behaviorKey: 'chase',
            behaviorParams: {
                speed: 1.0,
                trackingSpeed: 1.0,
                minDistance: 0
            }
        }
    },
    {
        key: 'enemy_centrao',
        enemy_body_image: 'src/assets/images/enemy_centrao.png',
        enemy_legs_image: 'src/assets/images/enemy_centrao_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.7,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_comunista',
        enemy_body_image: 'src/assets/images/enemy_comunista.png',
        enemy_legs_image: 'src/assets/images/enemy_comunista_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 0.9,
        legsScale: 0.6,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_feminista',
        enemy_body_image: 'src/assets/images/enemy_feminista.png',
        enemy_legs_image: 'src/assets/images/enemy_feminista_doida_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.45,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_feminista_doida',
        enemy_body_image: 'src/assets/images/enemy_feminista_doida.png',
        enemy_legs_image: 'src/assets/images/enemy_feminista_doida_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.45,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_history_teacher',
        enemy_body_image: 'src/assets/images/enemy_history_teacher.png',
        enemy_legs_image: 'src/assets/images/enemy_history_teacher_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.3,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_history_teacher2',
        enemy_body_image: 'src/assets/images/enemy_history_teacher2.png',
        enemy_legs_image: 'src/assets/images/enemy_history_teacher2_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.3,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_partido_amarelo',
        enemy_body_image: 'src/assets/images/enemy_partido_amarelo.png',
        enemy_legs_image: 'src/assets/images/enemy_petista_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 0.9,
        legsScale: 0.4,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_partido_amarelo2',
        enemy_body_image: 'src/assets/images/enemy_partido_amarelo2.png',
        enemy_legs_image: 'src/assets/images/enemy_petista_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 0.9,
        legsScale: 0.4,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_petista',
        enemy_body_image: 'src/assets/images/enemy_petista.png',
        enemy_legs_image: 'src/assets/images/enemy_petista_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 0.9,
        legsScale: 0.4,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_politico',
        enemy_body_image: 'src/assets/images/enemy_politico.png',
        enemy_legs_image: 'src/assets/images/enemy_politico_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.25,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    }
];

/**
 * Boss Configuration
 */
export const bossesConfig = [
    {
        key: 'boss_tia_zap',
        name: 'Tia do Zap',
        baseEnemy: 'enemy_tia_zap',
        healthMultiplier: 2,
        damageMultiplier: 2,
        speedMultiplier: 0.7,
        sizeMultiplier: 1.2,
        xpDropChance: 1.0,
        xpValue: 2,
        tint: 0xFFFFFF,
        enrageTint: 0xFF0000,
        enrageHealthThreshold: 0.5,
        enrageSpeedBonus: 0.2,
        stompInterval: 2000,
        gameplayRhythm: 0.5,
        dropChance: 1.0,
        lootTable: 'boss'
    },
    {
        key: 'boss_karl_marx',
        name: 'Karl Marx',
        baseEnemy: 'enemy_karl_marx',
        healthMultiplier: 2,
        damageMultiplier: 2,
        speedMultiplier: 0.7,
        sizeMultiplier: 1.2,
        xpDropChance: 1.0,
        xpValue: 2,
        tint: 0xFFFFFF,
        enrageTint: 0xFF0000,
        enrageHealthThreshold: 0.5,
        enrageSpeedBonus: 0.2,
        stompInterval: 2000,
        gameplayRhythm: 0.5,
        dropChance: 1.0,
        lootTable: 'boss'
    },
    {
        key: 'boss_bandido_moto',
        name: 'Dois homens numa moto',
        baseEnemy: 'enemy_bandido_moto',
        healthMultiplier: 1.5,
        damageMultiplier: 0.2,
        speedMultiplier: 0.7,
        sizeMultiplier: 1.6,
        xpDropChance: 1.0,
        xpValue: 2,
        tint: 0xFFFFFF,
        enrageTint: 0xFF0000,
        enrageHealthThreshold: 0.5,
        enrageSpeedBonus: 0.2,
        stompInterval: 2000,
        gameplayRhythm: 0.5,
        dropChance: 1.0,
        lootTable: 'boss'
    },
    {
        key: 'boss_tia_do_zap',
        name: 'Tia do Zap',
        baseEnemy: 'enemy_tia_do_zap',
        healthMultiplier: 2,
        damageMultiplier: 2,
        speedMultiplier: 0.7,
        sizeMultiplier: 1.5,
        xpDropChance: 1.0,
        xpValue: 2,
        tint: 0xFFFFFF,
        enrageTint: 0xFF0000,
        enrageHealthThreshold: 0.5,
        enrageSpeedBonus: 0.2,
        stompInterval: 2000,
        gameplayRhythm: 0.5,
        dropChance: 1.0,
        lootTable: 'boss'
    },
    {
        key: 'boss_crystal_golem',
        name: 'Golem de Cristal',
        baseEnemy: 'enemy_elite_crystal_2',
        healthMultiplier: 5,
        damageMultiplier: 3,
        speedMultiplier: 0.5,
        sizeMultiplier: 2.0,
        xpDropChance: 1.0,
        xpValue: 100,
        tint: 0xFFFFFF,
        enrageTint: 0xFF00FF,
        enrageHealthThreshold: 0.5,
        enrageSpeedBonus: 0.5,
        stompInterval: 3000,
        gameplayRhythm: 0.8,
        dropChance: 1.0,
        lootTable: 'boss'
    },
    {
        key: 'boss_bandido',
        name: 'Chefe do Tráfico',
        baseEnemy: 'enemy_boss_bandido',
        healthMultiplier: 1.5,
        damageMultiplier: 1.5,
        speedMultiplier: 1.0,
        sizeMultiplier: 1.0,
        xpDropChance: 1.0,
        xpValue: 500,
        tint: 0xFFFFFF,
        enrageTint: 0xFF0000,
        enrageHealthThreshold: 0.5,
        stompInterval: 2500,
        dropChance: 1.0,
        lootTable: 'boss'
    },
    {
        key: 'boss_milicia',
        name: 'Comandante da Milícia',
        baseEnemy: 'enemy_boss_milicia',
        healthMultiplier: 1.5,
        damageMultiplier: 2,
        speedMultiplier: 1.1,
        sizeMultiplier: 1.0,
        xpDropChance: 1.0,
        xpValue: 600,
        tint: 0xFFFFFF,
        enrageTint: 0xFF5500,
        enrageHealthThreshold: 0.4,
        stompInterval: 3000,
        dropChance: 1.0,
        lootTable: 'boss'
    },
    {
        key: 'boss_funkeiro',
        name: 'MC Latrocínio',
        baseEnemy: 'enemy_boss_funkeiro',
        healthMultiplier: 1.5,
        damageMultiplier: 1.5,
        speedMultiplier: 1.2,
        sizeMultiplier: 1.2,
        xpDropChance: 1.0,
        xpValue: 700,
        tint: 0xFFFFFF,
        enrageTint: 0xFF00FF,
        enrageHealthThreshold: 0.3,
        stompInterval: 1800,
        dropChance: 1.0,
        lootTable: 'boss'
    },
    {
        key: 'boss_teste',
        name: 'MC Latrocínio',
        baseEnemy: 'enemy_boss_funkeiro',
        healthMultiplier: 0.1,
        damageMultiplier: 1.5,
        speedMultiplier: 1.2,
        sizeMultiplier: 1.2,
        xpDropChance: 1.0,
        xpValue: 700,
        tint: 0xFFFFFF,
        enrageTint: 0xFF00FF,
        enrageHealthThreshold: 0.3,
        stompInterval: 1800,
        dropChance: 1.0,
        lootTable: 'boss'
    }
];
