/**
 * Enemy Configuration
 * 
 * Contains all enemy type definitions including base stats,
 * visual properties, and behavior configurations.
 */

export const enemiesConfig = [
    /* ------------ Enemies Favela ------------ */
    {
        key: 'enemy_favela_basico',
        enemy_body_image: 'src/assets/images/enemy_favela_basico.png',
        enemy_legs_image: 'src/assets/images/enemy_favela_basico_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 100,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.8,
        legsScale: 0.5,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'zigzag',
            behaviorParams: {
                baseSpeed: 1.0,
                amplitude: 50,
                frequency: 3.0
            }
        },
        scalingProfile: 'swarm'
    },
    {
        key: 'enemy_favela',
        enemy_body_image: 'src/assets/images/enemy_favela.png',
        enemy_legs_image: 'src/assets/images/enemy_favela_legs.png',
        speed: 120,
        size: 32,
        damage: 10,
        health: 50,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.4,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common',
        ai: {
            behaviorKey: 'chase',
            behaviorParams: {
                speed: 1.2,
                trackingSpeed: 0.8
            }
        }
    },
    {
        key: 'enemy_mendigo',
        enemy_body_image: 'src/assets/images/enemy_mendigo.png',
        enemy_legs_image: 'src/assets/images/enemy_mendigo_legs.png',
        speed: 80,
        size: 32,
        damage: 8,
        health: 40,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.7,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 45 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common',
        ai: {
            behaviorKey: 'zigzag',
            behaviorParams: {
                baseSpeed: 0.8,
                amplitude: 100,
                frequency: 1.5
            }
        }
    },
    {
        key: 'enemy_elite_bandido',
        enemy_body_image: 'src/assets/images/enemy_elite_bandido.png',
        enemy_legs_image: 'src/assets/images/enemy_elite_bandido_legs.png',
        speed: 140,
        size: 32,
        damage: 15,
        health: 200,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: true,
        projectileSpeed: 300,
        shootInterval: 3000,
        shootRange: 350,
        projectileDamage: 12,
        xpValue: 10,
        bodyScale: 0.7,
        legsScale: 0.7,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0xFF5500,
        projectileScale: 1.2,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        isElite: true,
        lootTable: 'common',
        ai: {
            behaviorKey: 'orbit',
            behaviorParams: {
                preferredDistance: 250,
                orbitSpeed: 0.9,
                approachSpeed: 1.2,
                orbitDirection: 1,
                distanceTolerance: 40
            }
        },
        scalingProfile: 'ranged'
    },
    {
        key: 'enemy_bandido_moto',
        enemy_body_image: 'src/assets/images/enemy_bandido_moto.png',
        enemy_legs_image: 'src/assets/images/enemy_bandido_legs.png',
        speed: 300,
        size: 35,
        damage: 25,
        health: 400,
        spawnDistance: 700,
        maxOnScreen: 5,
        xpDropChance: 1.0,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 20,
        bodyScale: 0.8,
        legsScale: 0,
        bodyWidth: 70,
        bodyHeight: 110,
        hitbox: { width: 50, height: 90 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0xFFFFFF,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.2,
        isElite: true,
        lootTable: 'rare',
        ai: {
            behaviorKey: 'charge',
            behaviorParams: {
                chargeUpTime: 800,
                chargeSpeed: 3.0,
                chargeDuration: 500,
                cooldownTime: 1500,
                idleSpeed: 0.3,
                lockDirection: true
            }
        },
        scalingProfile: 'aggressive'
    },
    {
        key: 'enemy_crime',
        enemy_body_image: 'src/assets/images/enemy_crime.png',
        enemy_legs_image: 'src/assets/images/enemy_crime_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 100,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 1,
        legsScale: 0.6,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: -10, y: 45 },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common'
    },
    {
        key: 'enemy_milicia',
        enemy_body_image: 'src/assets/images/enemy_milicia.png',
        enemy_legs_image: 'src/assets/images/enemy_milicia_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 100,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.8,
        legsScale: 0.5,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'chase',
            behaviorParams: {
                speed: 1.0,
                trackingSpeed: 0.4
            }
        },
        canShoot: true,
        projectileSpeed: 350,
        shootInterval: 2500,
        shootRange: 400,
        projectileDamage: 10
    },
    {
        key: 'enemy_milicia2',
        enemy_body_image: 'src/assets/images/enemy_milicia2.png',
        enemy_legs_image: 'src/assets/images/enemy_milicia_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 120,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: true,
        projectileSpeed: 300,
        shootInterval: 3500,
        shootRange: 300,
        projectileDamage: 12,
        xpValue: 1,
        bodyScale: 0.8,
        legsScale: 0.5,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0x00FF00,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'orbit',
            behaviorParams: {
                preferredDistance: 300,
                orbitSpeed: 0.7,
                approachSpeed: 1.0,
                orbitDirection: -1
            }
        }
    },
    {
        key: 'enemy_milicia3',
        enemy_body_image: 'src/assets/images/enemy_milicia3.png',
        enemy_legs_image: 'src/assets/images/enemy_milicia_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 120,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: true,
        projectileSpeed: 400,
        shootInterval: 2000,
        shootRange: 450,
        projectileDamage: 8,
        xpValue: 1,
        bodyScale: 0.8,
        legsScale: 0.5,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0x0000FF,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'zigzag',
            behaviorParams: {
                baseSpeed: 1.1,
                amplitude: 60,
                frequency: 2.5
            }
        }
    },
    {
        key: 'enemy_funkeiro',
        enemy_body_image: 'src/assets/images/enemy_funkeiro.png',
        enemy_legs_image: 'src/assets/images/enemy_funkeiro_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 100,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.8,
        legsScale: 0.5,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'charge',
            behaviorParams: {
                chargeUpTime: 1000,
                chargeSpeed: 2.5,
                chargeDuration: 600,
                cooldownTime: 2000,
                idleSpeed: 0.4
            }
        }
    },
    {
        key: 'enemy_funkeiro2',
        enemy_body_image: 'src/assets/images/enemy_funkeiro2.png',
        enemy_legs_image: 'src/assets/images/enemy_petista_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 100,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.8,
        legsScale: 0.5,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'burst_pursuit',
            behaviorParams: {
                pursuitSpeed: 1.6,
                pursuitDuration: 1000,
                pauseDuration: 500,
                pauseSpeed: 0.1
            }
        }
    },
    {
        key: 'enemy_funkeiro3',
        enemy_body_image: 'src/assets/images/enemy_funkeiro3.png',
        enemy_legs_image: 'src/assets/images/enemy_bandido_legs.png',
        speed: 200,
        size: 32,
        damage: 10,
        health: 80,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.7,
        legsScale: 0.4,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: -10, y: 30 },
        hitSoundKey: 'hit',
        dropChance: 0.08,
        lootTable: 'common',
        ai: {
            behaviorKey: 'burst_pursuit',
            behaviorParams: {
                pursuitSpeed: 1.5,
                pursuitDuration: 1000,
                pauseDuration: 800,
                pauseSpeed: 0
            }
        },
        scalingProfile: 'aggressive'
    },
    {
        key: 'enemy_cria',
        enemy_body_image: 'src/assets/images/enemy_cria.png',
        enemy_legs_image: 'src/assets/images/enemy_cria_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 100,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.8,
        legsScale: 0.5,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'flee',
            behaviorParams: {
                fleeSpeed: 1.3,
                triggerDistance: 180,
                safeDistance: 350,
                idleSpeed: 0.6
            }
        }
    },
    {
        key: 'enemy_cria2',
        enemy_body_image: 'src/assets/images/enemy_cria2.png',
        enemy_legs_image: 'src/assets/images/enemy_cria2_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 100,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.8,
        legsScale: 0.5,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'zigzag',
            behaviorParams: {
                baseSpeed: 1.2,
                amplitude: 40,
                frequency: 4.0
            }
        }
    },
    {
        key: 'enemy_influencer',
        enemy_body_image: 'src/assets/images/enemy_influencer.png',
        enemy_legs_image: 'src/assets/images/enemy_influencer_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 100,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.8,
        legsScale: 0.5,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'orbit',
            behaviorParams: {
                preferredDistance: 400,
                orbitSpeed: 0.6,
                approachSpeed: 0.8,
                orbitDirection: 1
            }
        },
        canShoot: true,
        projectileSpeed: 250,
        shootInterval: 4000,
        shootRange: 500,
        projectileDamage: 15
    },
    {
        key: 'enemy_influencer2',
        enemy_body_image: 'src/assets/images/enemy_influencer2.png',
        enemy_legs_image: 'src/assets/images/enemy_influencer2_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 100,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: true,
        projectileSpeed: 300,
        shootInterval: 3000,
        shootRange: 400,
        projectileDamage: 12,
        xpValue: 1,
        bodyScale: 0.8,
        legsScale: 0.5,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0xFFFF00,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'orbit',
            behaviorParams: {
                preferredDistance: 350,
                orbitSpeed: 0.8,
                approachSpeed: 1.0,
                orbitDirection: -1
            }
        }
    },
    {
        key: 'enemy_crime',
        enemy_body_image: 'src/assets/images/enemy_crime.png',
        enemy_legs_image: 'src/assets/images/enemy_crime_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 100,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.8,
        legsScale: 0.5,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'burst_pursuit',
            behaviorParams: {
                pursuitSpeed: 1.4,
                pursuitDuration: 1500,
                pauseDuration: 1000,
                pauseSpeed: 0.2
            }
        }
    },
    {
        key: 'enemy_crime2',
        enemy_body_image: 'src/assets/images/enemy_crime2.png',
        enemy_legs_image: 'src/assets/images/enemy_crime4_legs.png',
        speed: 130,
        size: 32,
        damage: 10,
        health: 120,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.9,
        legsScale: 0.6,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: -5, y: 40 },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'chase',
            behaviorParams: {
                speed: 1.3,
                trackingSpeed: 0.9
            }
        }
    },
    {
        key: 'enemy_crime3',
        enemy_body_image: 'src/assets/images/enemy_crime3.png',
        enemy_legs_image: 'src/assets/images/enemy_crime3_legs.png',
        speed: 100,
        size: 32,
        damage: 12,
        health: 150,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.9,
        legsScale: 0.6,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'charge',
            behaviorParams: {
                chargeUpTime: 700,
                chargeSpeed: 3.5,
                chargeDuration: 400,
                cooldownTime: 1800,
                idleSpeed: 0.2
            }
        }
    },
    {
        key: 'enemy_crime4',
        enemy_body_image: 'src/assets/images/enemy_crime4.png',
        enemy_legs_image: 'src/assets/images/enemy_crime4_legs.png',
        speed: 100,
        size: 32,
        damage: 10,
        health: 130,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 1,
        bodyScale: 0.9,
        legsScale: 0.7,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 42 },
        projectileColor: 0xFF0000,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common',
        ai: {
            behaviorKey: 'burst_pursuit',
            behaviorParams: {
                pursuitSpeed: 1.8,
                pursuitDuration: 2000,
                pauseDuration: 1000,
                pauseSpeed: 0
            }
        }
    },
    {
        key: 'enemy_crime5',
        enemy_body_image: 'src/assets/images/enemy_crime5.png',
        enemy_legs_image: 'src/assets/images/enemy_crime_legs.png',
        speed: 200,
        size: 32,
        damage: 15,
        health: 150,
        spawnDistance: 700,
        maxOnScreen: 40,
        xpDropChance: 0.9,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 0.9,
        legsScale: 0.6,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 45 },
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common',
        ai: {
            behaviorKey: 'charge',
            behaviorParams: {
                chargeUpTime: 800,
                chargeSpeed: 3.0,
                chargeDuration: 500,
                cooldownTime: 1500,
                idleSpeed: 0.3,
                lockDirection: true
            }
        },
        scalingProfile: 'aggressive'
    },
    /* -----------------------------*/
    {
        key: 'enemy_bolsonarista',
        enemy_body_image: 'src/assets/images/enemy_bolsonarista.png',
        enemy_legs_image: 'src/assets/images/enemy_bolsonarista_legs.png',
        speed: 250,
        size: 32,
        damage: 20,
        health: 40,
        spawnDistance: 700,
        maxOnScreen: 30,
        xpDropChance: 0.85,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 3,
        bodyScale: 1,
        legsScale: 1,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 5, y: 45 },
        hitSoundKey: 'hit',
        dropChance: 0.15,
        lootTable: 'ucommon',
        ai: {
            behaviorKey: 'orbit',
            behaviorParams: {
                preferredDistance: 200,
                orbitSpeed: 0.8,
                approachSpeed: 1.0,
                orbitDirection: 1,
                distanceTolerance: 30
            }
        },
        scalingProfile: 'ranged'
    },
    {
        key: 'enemy_bolsonarista2',
        enemy_body_image: 'src/assets/images/enemy_bolsonarista2.png',
        enemy_legs_image: 'src/assets/images/enemy_bolsonarista2_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.45,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: -10, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common',
        ai: {
            behaviorKey: 'chase',
            behaviorParams: {
                speed: 1.0,
                trackingSpeed: 1.0,
                minDistance: 0
            }
        }
    },
    {
        key: 'enemy_centrao',
        enemy_body_image: 'src/assets/images/enemy_centrao.png',
        enemy_legs_image: 'src/assets/images/enemy_centrao_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.7,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_comunista',
        enemy_body_image: 'src/assets/images/enemy_comunista.png',
        enemy_legs_image: 'src/assets/images/enemy_comunista_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 0.9,
        legsScale: 0.6,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_feminista',
        enemy_body_image: 'src/assets/images/enemy_feminista.png',
        enemy_legs_image: 'src/assets/images/enemy_feminista_doida_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.45,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_feminista_doida',
        enemy_body_image: 'src/assets/images/enemy_feminista_doida.png',
        enemy_legs_image: 'src/assets/images/enemy_feminista_doida_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.45,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_history_teacher',
        enemy_body_image: 'src/assets/images/enemy_history_teacher.png',
        enemy_legs_image: 'src/assets/images/enemy_history_teacher_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.3,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_history_teacher2',
        enemy_body_image: 'src/assets/images/enemy_history_teacher2.png',
        enemy_legs_image: 'src/assets/images/enemy_history_teacher2_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.3,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_partido_amarelo',
        enemy_body_image: 'src/assets/images/enemy_partido_amarelo.png',
        enemy_legs_image: 'src/assets/images/enemy_petista_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 0.9,
        legsScale: 0.4,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_partido_amarelo2',
        enemy_body_image: 'src/assets/images/enemy_partido_amarelo2.png',
        enemy_legs_image: 'src/assets/images/enemy_petista_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 0.9,
        legsScale: 0.4,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_petista',
        enemy_body_image: 'src/assets/images/enemy_petista.png',
        enemy_legs_image: 'src/assets/images/enemy_petista_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 0.9,
        legsScale: 0.4,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_politico',
        enemy_body_image: 'src/assets/images/enemy_politico.png',
        enemy_legs_image: 'src/assets/images/enemy_politico_legs.png',
        speed: 120,
        size: 32,
        damage: 8,
        health: 25,
        spawnDistance: 700,
        maxOnScreen: 50,
        xpDropChance: 0.75,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 1,
        legsScale: 0.25,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_elite_congresso_1',
        enemy_body_image: 'src/assets/images/enemy_elite_congresso_1.png',
        enemy_legs_image: 'src/assets/images/enemy_politico_legs.png',
        speed: 180,
        size: 35,
        damage: 15,
        health: 400,
        spawnDistance: 700,
        maxOnScreen: 8,
        xpDropChance: 1.0,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 12,
        bodyScale: 0.8,
        legsScale: 0.5,
        bodyWidth: 70,
        bodyHeight: 110,
        hitbox: { width: 50, height: 90 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.25,
        isElite: true,
        lootTable: 'uncommon'
    },
    {
        key: 'enemy_elite_congresso_2',
        enemy_body_image: 'src/assets/images/enemy_elite_congresso_2.png',
        enemy_legs_image: 'src/assets/images/enemy_politico_legs.png',
        speed: 120,
        size: 45,
        damage: 30,
        health: 600,
        spawnDistance: 700,
        maxOnScreen: 4,
        xpDropChance: 1.0,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 20,
        bodyScale: 1.1,
        legsScale: 0.6,
        bodyWidth: 110,
        bodyHeight: 150,
        hitbox: { width: 90, height: 130 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0x9966FF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.35,
        isElite: true,
        lootTable: 'rare'
    },
    {
        key: 'enemy_elite_avenida_1',
        enemy_body_image: 'src/assets/images/enemy_elite_avenida_1.png',
        enemy_legs_image: 'src/assets/images/enemy_bolsonarista_legs.png',
        speed: 200,
        size: 40,
        damage: 20,
        health: 350,
        spawnDistance: 700,
        maxOnScreen: 7,
        xpDropChance: 1.0,
        canShoot: true,
        projectileSpeed: 500,
        shootInterval: 1500,
        shootRange: 600,
        projectileDamage: 10,
        xpValue: 18,
        bodyScale: 0.9,
        legsScale: 0.8,
        bodyWidth: 80,
        bodyHeight: 120,
        hitbox: { width: 60, height: 100 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0xFFFF00,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.3,
        isElite: true,
        lootTable: 'uncommon'
    },
    {
        key: 'enemy_elite_avenida_2',
        enemy_body_image: 'src/assets/images/enemy_elite_avenida_2.png',
        enemy_legs_image: 'src/assets/images/enemy_bolsonarista_legs.png',
        speed: 150,
        size: 50,
        damage: 35,
        health: 700,
        spawnDistance: 700,
        maxOnScreen: 3,
        xpDropChance: 1.0,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 25,
        bodyScale: 1.2,
        legsScale: 0.9,
        bodyWidth: 120,
        bodyHeight: 160,
        hitbox: { width: 100, height: 140 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0xFFFFFF,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.4,
        isElite: true,
        lootTable: 'rare'
    },
    {
        key: 'enemy_common_1',
        enemy_body_image: 'src/assets/images/enemy_common_1.png',
        enemy_legs_image: 'src/assets/images/enemy_bandido_legs.png',
        speed: 250,
        size: 28,
        damage: 12,
        health: 60,
        spawnDistance: 700,
        maxOnScreen: 20,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 2,
        bodyScale: 0.6,
        legsScale: 0.4,
        bodyWidth: 50,
        bodyHeight: 90,
        hitbox: { width: 30, height: 70 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 30 },
        projectileColor: 0xFFFFFF,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.05,
        lootTable: 'common'
    },
    {
        key: 'enemy_common_2',
        enemy_body_image: 'src/assets/images/enemy_common_2.png',
        enemy_legs_image: 'src/assets/images/enemy_centrao_legs.png',
        speed: 100,
        size: 40,
        damage: 18,
        health: 200,
        spawnDistance: 700,
        maxOnScreen: 15,
        xpDropChance: 0.9,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 3,
        bodyScale: 0.9,
        legsScale: 0.6,
        bodyWidth: 70,
        bodyHeight: 110,
        hitbox: { width: 50, height: 90 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0xFFFFFF,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_common_3',
        enemy_body_image: 'src/assets/images/enemy_common_3.png',
        enemy_legs_image: 'src/assets/images/enemy_petista_legs.png',
        speed: 180,
        size: 32,
        damage: 10,
        health: 100,
        spawnDistance: 700,
        maxOnScreen: 25,
        xpDropChance: 0.85,
        canShoot: true,
        projectileSpeed: 300,
        shootInterval: 3000,
        shootRange: 400,
        projectileDamage: 8,
        xpValue: 4,
        bodyScale: 0.7,
        legsScale: 0.5,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 35 },
        projectileColor: 0x00FF00,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.08,
        lootTable: 'common'
    },
    {
        key: 'enemy_elite_congresso_3',
        enemy_body_image: 'src/assets/images/enemy_elite_congresso_3.png',
        enemy_legs_image: 'src/assets/images/enemy_politico_legs.png',
        speed: 150,
        size: 50,
        damage: 40,
        health: 800,
        spawnDistance: 700,
        maxOnScreen: 2,
        xpDropChance: 1.0,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 30,
        bodyScale: 1.3,
        legsScale: 0.7,
        bodyWidth: 130,
        bodyHeight: 170,
        hitbox: { width: 110, height: 150 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 60 },
        projectileColor: 0xFFFFFF,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.5,
        isElite: true,
        lootTable: 'rare'
    },
    {
        key: 'enemy_elite_avenida_3',
        enemy_body_image: 'src/assets/images/enemy_elite_avenida_3.png',
        enemy_legs_image: 'src/assets/images/enemy_bolsonarista_legs.png',
        speed: 220,
        size: 45,
        damage: 30,
        health: 600,
        spawnDistance: 700,
        maxOnScreen: 4,
        xpDropChance: 1.0,
        canShoot: true,
        projectileSpeed: 600,
        shootInterval: 1000,
        shootRange: 700,
        projectileDamage: 15,
        xpValue: 28,
        bodyScale: 1.0,
        legsScale: 0.9,
        bodyWidth: 90,
        bodyHeight: 130,
        hitbox: { width: 70, height: 110 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0xFF00FF,
        projectileScale: 1.2,
        hitSoundKey: 'hit',
        dropChance: 0.4,
        isElite: true,
        lootTable: 'rare'
    },
    {
        key: 'enemy_common_crystal_1',
        enemy_body_image: 'src/assets/images/enemy_common_crystal_1.png',
        enemy_legs_image: 'src/assets/images/enemy_crystal_legs.png',
        speed: 150,
        size: 30,
        damage: 15,
        health: 120,
        spawnDistance: 700,
        maxOnScreen: 30,
        xpDropChance: 0.8,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 5,
        bodyScale: 0.7,
        legsScale: 0.5,
        bodyWidth: 60,
        bodyHeight: 100,
        hitbox: { width: 40, height: 80 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0xFFFFFF,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.1,
        lootTable: 'common'
    },
    {
        key: 'enemy_common_crystal_2',
        enemy_body_image: 'src/assets/images/enemy_common_crystal_2.png',
        enemy_legs_image: 'src/assets/images/enemy_crystal_legs.png',
        speed: 120,
        size: 38,
        damage: 20,
        health: 250,
        spawnDistance: 700,
        maxOnScreen: 20,
        xpDropChance: 0.85,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 7,
        bodyScale: 0.9,
        legsScale: 0.6,
        bodyWidth: 80,
        bodyHeight: 120,
        hitbox: { width: 60, height: 100 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0xFFFFFF,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.15,
        lootTable: 'common'
    },
    {
        key: 'enemy_common_crystal_3',
        enemy_body_image: 'src/assets/images/enemy_common_crystal_3.png',
        enemy_legs_image: 'src/assets/images/enemy_crystal_legs.png',
        speed: 200,
        size: 25,
        damage: 10,
        health: 80,
        spawnDistance: 700,
        maxOnScreen: 40,
        xpDropChance: 0.75,
        canShoot: true,
        projectileSpeed: 400,
        shootInterval: 2500,
        shootRange: 500,
        projectileDamage: 10,
        xpValue: 6,
        bodyScale: 0.6,
        legsScale: 0.4,
        bodyWidth: 50,
        bodyHeight: 90,
        hitbox: { width: 30, height: 70 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 30 },
        projectileColor: 0x00FFFF,
        projectileScale: 0.8,
        hitSoundKey: 'hit',
        dropChance: 0.12,
        lootTable: 'common'
    },
    {
        key: 'enemy_common_crystal_4',
        enemy_body_image: 'src/assets/images/enemy_common_crystal_4.png',
        enemy_legs_image: 'src/assets/images/enemy_crystal_legs.png',
        speed: 80,
        size: 45,
        damage: 25,
        health: 400,
        spawnDistance: 700,
        maxOnScreen: 10,
        xpDropChance: 0.9,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 10,
        bodyScale: 1.1,
        legsScale: 0.7,
        bodyWidth: 100,
        bodyHeight: 140,
        hitbox: { width: 80, height: 120 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 60 },
        projectileColor: 0xFFFFFF,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.2,
        lootTable: 'uncommon'
    },
    {
        key: 'enemy_common_crystal_5',
        enemy_body_image: 'src/assets/images/enemy_common_crystal_5.png',
        enemy_legs_image: 'src/assets/images/enemy_crystal_legs.png',
        speed: 180,
        size: 32,
        damage: 18,
        health: 150,
        spawnDistance: 700,
        maxOnScreen: 25,
        xpDropChance: 0.8,
        canShoot: true,
        projectileSpeed: 500,
        shootInterval: 2000,
        shootRange: 600,
        projectileDamage: 12,
        xpValue: 8,
        bodyScale: 0.8,
        legsScale: 0.5,
        bodyWidth: 70,
        bodyHeight: 110,
        hitbox: { width: 50, height: 90 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 40 },
        projectileColor: 0xFF00FF,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.18,
        lootTable: 'uncommon'
    },
    {
        key: 'enemy_elite_crystal_1',
        enemy_body_image: 'src/assets/images/enemy_elite_crystal_1.png',
        enemy_legs_image: 'src/assets/images/enemy_crystal_legs.png',
        speed: 250,
        size: 40,
        damage: 30,
        health: 600,
        spawnDistance: 700,
        maxOnScreen: 5,
        xpDropChance: 1.0,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 35,
        bodyScale: 1.0,
        legsScale: 0.7,
        bodyWidth: 90,
        bodyHeight: 130,
        hitbox: { width: 70, height: 110 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 50 },
        projectileColor: 0xFFFFFF,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.4,
        isElite: true,
        lootTable: 'rare'
    },
    {
        key: 'enemy_elite_crystal_2',
        enemy_body_image: 'src/assets/images/enemy_elite_crystal_2.png',
        enemy_legs_image: 'src/assets/images/enemy_crystal_legs.png',
        speed: 180,
        size: 55,
        damage: 50,
        health: 1200,
        spawnDistance: 700,
        maxOnScreen: 2,
        xpDropChance: 1.0,
        canShoot: false,
        projectileSpeed: 0,
        shootInterval: 0,
        shootRange: 0,
        projectileDamage: 0,
        xpValue: 50,
        bodyScale: 1.4,
        legsScale: 0.8,
        bodyWidth: 140,
        bodyHeight: 180,
        hitbox: { width: 120, height: 160 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 70 },
        projectileColor: 0xFFFFFF,
        projectileScale: 1.0,
        hitSoundKey: 'hit',
        dropChance: 0.6,
        isElite: true,
        lootTable: 'rare'
    },
    {
        key: 'enemy_elite_crystal_3',
        enemy_body_image: 'src/assets/images/enemy_elite_crystal_3.png',
        enemy_legs_image: 'src/assets/images/enemy_crystal_legs.png',
        speed: 200,
        size: 48,
        damage: 40,
        health: 900,
        spawnDistance: 700,
        maxOnScreen: 3,
        xpDropChance: 1.0,
        canShoot: true,
        projectileSpeed: 700,
        shootInterval: 800,
        shootRange: 800,
        projectileDamage: 20,
        xpValue: 45,
        bodyScale: 1.2,
        legsScale: 0.9,
        bodyWidth: 110,
        bodyHeight: 150,
        hitbox: { width: 90, height: 130 },
        bossScale: 0.6,
        legOffset: { x: 0, y: 60 },
        projectileColor: 0x00FFFF,
        projectileScale: 1.4,
        hitSoundKey: 'hit',
        dropChance: 0.5,
        isElite: true,
        lootTable: 'rare'
    }
];

/**
 * Boss Configuration
 */
export const bossesConfig = [
    {
        key: 'boss_tia_zap',
        name: 'Tia do Zap',
        baseEnemy: 'enemy_tia_zap',
        healthMultiplier: 2,
        damageMultiplier: 2,
        speedMultiplier: 0.7,
        sizeMultiplier: 1.2,
        xpDropChance: 1.0,
        xpValue: 2,
        tint: 0xFFFFFF,
        enrageTint: 0xFF0000,
        enrageHealthThreshold: 0.5,
        enrageSpeedBonus: 0.2,
        stompInterval: 2000,
        gameplayRhythm: 0.5,
        dropChance: 1.0,
        lootTable: 'boss'
    },
    {
        key: 'boss_karl_marx',
        name: 'Karl Marx',
        baseEnemy: 'enemy_karl_marx',
        healthMultiplier: 2,
        damageMultiplier: 2,
        speedMultiplier: 0.7,
        sizeMultiplier: 1.2,
        xpDropChance: 1.0,
        xpValue: 2,
        tint: 0xFFFFFF,
        enrageTint: 0xFF0000,
        enrageHealthThreshold: 0.5,
        enrageSpeedBonus: 0.2,
        stompInterval: 2000,
        gameplayRhythm: 0.5,
        dropChance: 1.0,
        lootTable: 'boss'
    },
    {
        key: 'boss_bandido_moto',
        name: 'Dois homens numa moto',
        baseEnemy: 'enemy_bandido_moto',
        healthMultiplier: 2,
        damageMultiplier: 2,
        speedMultiplier: 0.7,
        sizeMultiplier: 1.6,
        xpDropChance: 1.0,
        xpValue: 2,
        tint: 0xFFFFFF,
        enrageTint: 0xFF0000,
        enrageHealthThreshold: 0.5,
        enrageSpeedBonus: 0.2,
        stompInterval: 2000,
        gameplayRhythm: 0.5,
        dropChance: 1.0,
        lootTable: 'boss'
    },
    {
        key: 'boss_tia_do_zap',
        name: 'Tia do Zap',
        baseEnemy: 'enemy_tia_do_zap',
        healthMultiplier: 2,
        damageMultiplier: 2,
        speedMultiplier: 0.7,
        sizeMultiplier: 1.5,
        xpDropChance: 1.0,
        xpValue: 2,
        tint: 0xFFFFFF,
        enrageTint: 0xFF0000,
        enrageHealthThreshold: 0.5,
        enrageSpeedBonus: 0.2,
        stompInterval: 2000,
        gameplayRhythm: 0.5,
        dropChance: 1.0,
        lootTable: 'boss'
    },
    {
        key: 'boss_crystal_golem',
        name: 'Golem de Cristal',
        baseEnemy: 'enemy_elite_crystal_2',
        healthMultiplier: 5,
        damageMultiplier: 3,
        speedMultiplier: 0.5,
        sizeMultiplier: 2.0,
        xpDropChance: 1.0,
        xpValue: 100,
        tint: 0xFFFFFF,
        enrageTint: 0xFF00FF,
        enrageHealthThreshold: 0.5,
        enrageSpeedBonus: 0.5,
        stompInterval: 3000,
        gameplayRhythm: 0.8,
        dropChance: 1.0,
        lootTable: 'boss'
    }
];
